version: "3.8"

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - monitoring
    volumes:
      - .:/backend

  
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - monitoring
    volumes:
      - redis_data:/data


networks:
  monitoring:
    driver: bridge

volumes:
  redis_data: