"""removed rank from game score table |  migration

Revision ID: 5e7cff2e2b02
Revises: daa78ca5b03e
Create Date: 2025-02-10 02:55:24.409487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e7cff2e2b02'
down_revision: Union[str, None] = 'daa78ca5b03e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_scores', 'rank')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_scores', sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
