"""updated gameScore tbale to game session table |  migration

Revision ID: 72254c9e80ca
Revises: a06fb907a166
Create Date: 2025-02-10 04:53:47.810967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72254c9e80ca'
down_revision: Union[str, None] = 'a06fb907a166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
