"""added a game status model |  migration

Revision ID: ad9cdeca7420
Revises: 4c254e8b2d0f
Create Date: 2025-02-11 00:38:34.416391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad9cdeca7420'
down_revision: Union[str, None] = '4c254e8b2d0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
