"""updated gameScore tbale to game session table |  migration

Revision ID: e689f80f2ba9
Revises: 5e7cff2e2b02
Create Date: 2025-02-10 04:39:07.337831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e689f80f2ba9'
down_revision: Union[str, None] = '5e7cff2e2b02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('game_status', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_session_id'), 'game_session', ['id'], unique=False)
    op.drop_index('ix_game_scores_id', table_name='game_scores')
    op.drop_table('game_scores')
    op.add_column('games', sa.Column('upvotes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'upvotes')
    op.create_table('game_scores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name='game_scores_game_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='game_scores_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='game_scores_pkey')
    )
    op.create_index('ix_game_scores_id', 'game_scores', ['id'], unique=False)
    op.drop_index(op.f('ix_game_session_id'), table_name='game_session')
    op.drop_table('game_session')
    # ### end Alembic commands ###
