"""RDS MUMBAI MIGRATION

Revision ID: eb99135d95dd
Revises: 73a78fe34e5b
Create Date: 2025-02-11 12:28:30.713897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb99135d95dd'
down_revision: Union[str, None] = '73a78fe34e5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
